language: php
php:
    - 5.6
    - 7.0
    - 7.1

script: ./tests/run.sh -s $NTESTER_FLAGS ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    - composer install --no-interaction --prefer-source

    - cp ./tests/php.unix-sample.ini ./tests/php.ini

    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -c tests/.coveralls.yml -v; fi
